rules = ('scissors cut paper, \n'
         'paper covers rock, \n'
         'rock crushes lizard, \n'
         'lizard poisons Spock, \n'
         'Spock smashes scissors, \n'
         'scissors decapitate lizard, \n'
         'lizard eats paper, \n'
         'paper disproves Spock, \n'
         'Spock vaporizes rock, \n'
         'rock crushes scissors')
