rules = ('rock pounds out fire, \n'
         'rock crushes scissors, \n'
         'rock crushes sponge, \n'
         'fire melts scissors, \n'
         'fire burns paper, \n'
         'fire burns sponge, \n'
         'scissors swish through air, \n'
         'scissors cut paper, \n'
         'scissors cut sponge, \n'
         'sponge soaks paper, \n'
         'sponge uses air, \n'
         'sponge absorbs water, \n'
         'paper fans air, \n'
         'paper covers rock, \n'
         'paper floats on water, \n'
         'air blows out fire, \n'
         'air erodes rock, \n'
         'air evaporates water, \n'
         'water erodes rock, \n'
         'water puts out fire, \n'
         'water rusts scissors')
